apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  minReadySeconds: 10 # by default is 0
  podManagementPolicy: Parallel # default is OrderedReady
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.24
        ports:
        - containerPort: 80
          name: web
        volumeMounts: # if fsType is block then this needs to be volumeDevices:
        - name: www
          mountPath: /usr/share/nginx/html # if fsType is block then this needs to be devicePath: /dev/www
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: topolvm-provisioner
      # volumeMode: Block
      resources:
        requests:
          storage: 300Mi # for storageClass.fsType: xfs 300Mi is the minimum, ext4 is 32Mi and block is 8Mi (needs a bit different configuration)
