controller:
  replicaCount: 1

lvmd:
  managed: false

cert-manager:
  enabled: true

# Take this out if no Tiltfile is used
image:
  repository: ttl.sh/topolvm-local

storageClasses:
  - name: topolvm-provisioner
    storageClass:
      fsType: xfs # This can be changed to xfs, ext4 or block
      isDefaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      additionalParameters:
      "topolvm.io/device-class": "ssd"
  - name: topolvm-provisioner-thin
    storageClass:
      fsType: xfs # This can be changed to xfs, ext4 or block
      isDefaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      additionalParameters:
        "topolvm.io/device-class": "ssd-thin"
