controller:
  replicaCount: 1

lvmd:
  managed: false

cert-manager:
  enabled: true

storageClasses:
  - name: topolvm-provisioner
    storageClass:
      fsType: ext4 # This can be changed to xfs, ext4 or block
      isDefaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      additionalParameters:
      "topolvm.io/device-class": "ssd"
  - name: topolvm-provisioner-thin
    storageClass:
      fsType: ext4 # This can be changed to xfs, ext4 or block
      isDefaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      additionalParameters:
        "topolvm.io/device-class": "ssd-thin"
